// Sample student data for Chess Empire - Expanded to 70 students across 7 branches
const students = [
    // Gagarin Park Branch (10 students)
    {
        id: 1,
        firstName: "Aidar",
        lastName: "Amanov",
        age: 12,
        branch: "Gagarin Park",
        coach: "Nurgalimov Chingis",
        razryad: "2nd",
        status: "active",
        currentLevel: 5,
        currentLesson: 28,
        totalLessons: 40
    },
    {
        id: 2,
        firstName: "Damir",
        lastName: "Nurlan",
        age: 10,
        branch: "Gagarin Park",
        coach: "Nurgalimov Chingis",
        razryad: "3rd",
        status: "active",
        currentLevel: 3,
        currentLesson: 15,
        totalLessons: 40
    },
    {
        id: 3,
        firstName: "Arman",
        lastName: "Serik",
        age: 14,
        branch: "Gagarin Park",
        coach: "Nurgalimov Chingis",
        razryad: "KMS",
        status: "active",
        currentLevel: 7,
        currentLesson: 32,
        totalLessons: 40
    },
    {
        id: 4,
        firstName: "Zhanna",
        lastName: "Mukhtar",
        age: 11,
        branch: "Gagarin Park",
        coach: "Nurgalimov Chingis",
        razryad: "3rd",
        status: "active",
        currentLevel: 4,
        currentLesson: 20,
        totalLessons: 40
    },
    {
        id: 5,
        firstName: "Timur",
        lastName: "Bakyt",
        age: 9,
        branch: "Gagarin Park",
        coach: "Nurgalimov Chingis",
        razryad: null,
        status: "active",
        currentLevel: 2,
        currentLesson: 8,
        totalLessons: 40
    },
    {
        id: 6,
        firstName: "Nurlana",
        lastName: "Akhmet",
        age: 13,
        branch: "Gagarin Park",
        coach: "Nurgalimov Chingis",
        razryad: "1st",
        status: "active",
        currentLevel: 6,
        currentLesson: 25,
        totalLessons: 40
    },
    {
        id: 7,
        firstName: "Erlan",
        lastName: "Suleimenov",
        age: 12,
        branch: "Gagarin Park",
        coach: "Nurgalimov Chingis",
        razryad: "2nd",
        status: "active",
        currentLevel: 5,
        currentLesson: 18,
        totalLessons: 40
    },
    {
        id: 8,
        firstName: "Aliya",
        lastName: "Bekbosyn",
        age: 10,
        branch: "Gagarin Park",
        coach: "Nurgalimov Chingis",
        razryad: null,
        status: "active",
        currentLevel: 3,
        currentLesson: 12,
        totalLessons: 40
    },
    {
        id: 9,
        firstName: "Ruslan",
        lastName: "Kanatov",
        age: 15,
        branch: "Gagarin Park",
        coach: "Nurgalimov Chingis",
        razryad: "KMS",
        status: "active",
        currentLevel: 8,
        currentLesson: 35,
        totalLessons: 40
    },
    {
        id: 10,
        firstName: "Asel",
        lastName: "Tolegenova",
        age: 11,
        branch: "Gagarin Park",
        coach: "Nurgalimov Chingis",
        razryad: "3rd",
        status: "active",
        currentLevel: 4,
        currentLesson: 22,
        totalLessons: 40
    },

    // Debut Branch (10 students)
    {
        id: 11,
        firstName: "Sultan",
        lastName: "Omarov",
        age: 13,
        branch: "Debut",
        coach: "Asylkhan Akbaevich",
        razryad: "1st",
        status: "active",
        currentLevel: 6,
        currentLesson: 27,
        totalLessons: 40
    },
    {
        id: 12,
        firstName: "Dana",
        lastName: "Yessimova",
        age: 9,
        branch: "Debut",
        coach: "Asylkhan Akbaevich",
        razryad: null,
        status: "active",
        currentLevel: 2,
        currentLesson: 9,
        totalLessons: 40
    },
    {
        id: 13,
        firstName: "Alibek",
        lastName: "Nurpeisov",
        age: 14,
        branch: "Debut",
        coach: "Asylkhan Akbaevich",
        razryad: "KMS",
        status: "active",
        currentLevel: 7,
        currentLesson: 30,
        totalLessons: 40
    },
    {
        id: 14,
        firstName: "Aruzhan",
        lastName: "Mukanova",
        age: 10,
        branch: "Debut",
        coach: "Asylkhan Akbaevich",
        razryad: "3rd",
        status: "active",
        currentLevel: 3,
        currentLesson: 14,
        totalLessons: 40
    },
    {
        id: 15,
        firstName: "Daniyar",
        lastName: "Kenzhebaev",
        age: 12,
        branch: "Debut",
        coach: "Asylkhan Akbaevich",
        razryad: "2nd",
        status: "active",
        currentLevel: 5,
        currentLesson: 21,
        totalLessons: 40
    },
    {
        id: 16,
        firstName: "Ayana",
        lastName: "Tashenova",
        age: 11,
        branch: "Debut",
        coach: "Asylkhan Akbaevich",
        razryad: "3rd",
        status: "active",
        currentLevel: 4,
        currentLesson: 18,
        totalLessons: 40
    },
    {
        id: 17,
        firstName: "Yerbol",
        lastName: "Akhmetov",
        age: 15,
        branch: "Debut",
        coach: "Asylkhan Akbaevich",
        razryad: "KMS",
        status: "active",
        currentLevel: 8,
        currentLesson: 36,
        totalLessons: 40
    },
    {
        id: 18,
        firstName: "Kamila",
        lastName: "Baizhanova",
        age: 9,
        branch: "Debut",
        coach: "Asylkhan Akbaevich",
        razryad: null,
        status: "active",
        currentLevel: 2,
        currentLesson: 7,
        totalLessons: 40
    },
    {
        id: 19,
        firstName: "Azamat",
        lastName: "Tursynov",
        age: 13,
        branch: "Debut",
        coach: "Asylkhan Akbaevich",
        razryad: "1st",
        status: "active",
        currentLevel: 6,
        currentLesson: 29,
        totalLessons: 40
    },
    {
        id: 20,
        firstName: "Madina",
        lastName: "Sabitova",
        age: 10,
        branch: "Debut",
        coach: "Asylkhan Akbaevich",
        razryad: "3rd",
        status: "active",
        currentLevel: 3,
        currentLesson: 13,
        totalLessons: 40
    },

    // Almaty Arena Branch (10 students)
    {
        id: 21,
        firstName: "Dias",
        lastName: "Zhanuzakov",
        age: 12,
        branch: "Almaty Arena",
        coach: "Tanibergen Aibekovich",
        razryad: "2nd",
        status: "active",
        currentLevel: 5,
        currentLesson: 24,
        totalLessons: 40
    },
    {
        id: 22,
        firstName: "Aizere",
        lastName: "Ospanova",
        age: 8,
        branch: "Almaty Arena",
        coach: "Tanibergen Aibekovich",
        razryad: null,
        status: "active",
        currentLevel: 1,
        currentLesson: 5,
        totalLessons: 40
    },
    {
        id: 23,
        firstName: "Nurbolat",
        lastName: "Bissembaev",
        age: 14,
        branch: "Almaty Arena",
        coach: "Tanibergen Aibekovich",
        razryad: "1st",
        status: "active",
        currentLevel: 7,
        currentLesson: 31,
        totalLessons: 40
    },
    {
        id: 24,
        firstName: "Aigerim",
        lastName: "Tleuova",
        age: 11,
        branch: "Almaty Arena",
        coach: "Tanibergen Aibekovich",
        razryad: "3rd",
        status: "active",
        currentLevel: 4,
        currentLesson: 19,
        totalLessons: 40
    },
    {
        id: 25,
        firstName: "Bauyrzhan",
        lastName: "Orazov",
        age: 13,
        branch: "Almaty Arena",
        coach: "Tanibergen Aibekovich",
        razryad: "2nd",
        status: "active",
        currentLevel: 6,
        currentLesson: 26,
        totalLessons: 40
    },
    {
        id: 26,
        firstName: "Inzhu",
        lastName: "Kabdrakhmanova",
        age: 10,
        branch: "Almaty Arena",
        coach: "Tanibergen Aibekovich",
        razryad: null,
        status: "active",
        currentLevel: 3,
        currentLesson: 11,
        totalLessons: 40
    },
    {
        id: 27,
        firstName: "Miras",
        lastName: "Aitzhanov",
        age: 15,
        branch: "Almaty Arena",
        coach: "Tanibergen Aibekovich",
        razryad: "KMS",
        status: "active",
        currentLevel: 8,
        currentLesson: 37,
        totalLessons: 40
    },
    {
        id: 28,
        firstName: "Balzhan",
        lastName: "Kudaibergenova",
        age: 9,
        branch: "Almaty Arena",
        coach: "Tanibergen Aibekovich",
        razryad: null,
        status: "active",
        currentLevel: 2,
        currentLesson: 10,
        totalLessons: 40
    },
    {
        id: 29,
        firstName: "Sanjar",
        lastName: "Kenzhetaev",
        age: 12,
        branch: "Almaty Arena",
        coach: "Tanibergen Aibekovich",
        razryad: "2nd",
        status: "active",
        currentLevel: 5,
        currentLesson: 23,
        totalLessons: 40
    },
    {
        id: 30,
        firstName: "Akerke",
        lastName: "Nazarbayeva",
        age: 11,
        branch: "Almaty Arena",
        coach: "Tanibergen Aibekovich",
        razryad: "3rd",
        status: "active",
        currentLevel: 4,
        currentLesson: 17,
        totalLessons: 40
    },

    // Halyk Arena Branch (10 students)
    {
        id: 31,
        firstName: "Aslan",
        lastName: "Mukashev",
        age: 13,
        branch: "Halyk Arena",
        coach: "Alinur Serikovich",
        razryad: "1st",
        status: "active",
        currentLevel: 6,
        currentLesson: 28,
        totalLessons: 40
    },
    {
        id: 32,
        firstName: "Aisulu",
        lastName: "Kenzhegazyeva",
        age: 8,
        branch: "Halyk Arena",
        coach: "Alinur Serikovich",
        razryad: null,
        status: "active",
        currentLevel: 1,
        currentLesson: 4,
        totalLessons: 40
    },
    {
        id: 33,
        firstName: "Darkhan",
        lastName: "Zhumabayev",
        age: 14,
        branch: "Halyk Arena",
        coach: "Alinur Serikovich",
        razryad: "KMS",
        status: "active",
        currentLevel: 7,
        currentLesson: 33,
        totalLessons: 40
    },
    {
        id: 34,
        firstName: "Zarina",
        lastName: "Mynbayeva",
        age: 10,
        branch: "Halyk Arena",
        coach: "Alinur Serikovich",
        razryad: "3rd",
        status: "active",
        currentLevel: 3,
        currentLesson: 16,
        totalLessons: 40
    },
    {
        id: 35,
        firstName: "Rauan",
        lastName: "Sarsembaev",
        age: 12,
        branch: "Halyk Arena",
        coach: "Alinur Serikovich",
        razryad: "2nd",
        status: "active",
        currentLevel: 5,
        currentLesson: 25,
        totalLessons: 40
    },
    {
        id: 36,
        firstName: "Nazgul",
        lastName: "Beisembina",
        age: 11,
        branch: "Halyk Arena",
        coach: "Khantuev Alexander",
        razryad: "3rd",
        status: "active",
        currentLevel: 4,
        currentLesson: 20,
        totalLessons: 40
    },
    {
        id: 37,
        firstName: "Arsen",
        lastName: "Bektasov",
        age: 15,
        branch: "Halyk Arena",
        coach: "Khantuev Alexander",
        razryad: "KMS",
        status: "active",
        currentLevel: 8,
        currentLesson: 38,
        totalLessons: 40
    },
    {
        id: 38,
        firstName: "Togzhan",
        lastName: "Abdrakhmanova",
        age: 9,
        branch: "Halyk Arena",
        coach: "Khantuev Alexander",
        razryad: null,
        status: "active",
        currentLevel: 2,
        currentLesson: 6,
        totalLessons: 40
    },
    {
        id: 39,
        firstName: "Bekzat",
        lastName: "Yergaliev",
        age: 13,
        branch: "Halyk Arena",
        coach: "Khantuev Alexander",
        razryad: "1st",
        status: "active",
        currentLevel: 6,
        currentLesson: 27,
        totalLessons: 40
    },
    {
        id: 40,
        firstName: "Aiym",
        lastName: "Zholdybayeva",
        age: 10,
        branch: "Halyk Arena",
        coach: "Khantuev Alexander",
        razryad: "3rd",
        status: "active",
        currentLevel: 3,
        currentLesson: 15,
        totalLessons: 40
    },

    // Zhandosova Branch (10 students)
    {
        id: 41,
        firstName: "Talgat",
        lastName: "Sarsenbayev",
        age: 12,
        branch: "Zhandosova",
        coach: "Zakir Anvarovich",
        razryad: "2nd",
        status: "active",
        currentLevel: 5,
        currentLesson: 22,
        totalLessons: 40
    },
    {
        id: 42,
        firstName: "Samal",
        lastName: "Kuandykova",
        age: 9,
        branch: "Zhandosova",
        coach: "Zakir Anvarovich",
        razryad: null,
        status: "active",
        currentLevel: 2,
        currentLesson: 8,
        totalLessons: 40
    },
    {
        id: 43,
        firstName: "Kairat",
        lastName: "Zhunisov",
        age: 14,
        branch: "Zhandosova",
        coach: "Zakir Anvarovich",
        razryad: "1st",
        status: "active",
        currentLevel: 7,
        currentLesson: 32,
        totalLessons: 40
    },
    {
        id: 44,
        firstName: "Symbat",
        lastName: "Aitbayeva",
        age: 11,
        branch: "Zhandosova",
        coach: "Zakir Anvarovich",
        razryad: "3rd",
        status: "active",
        currentLevel: 4,
        currentLesson: 18,
        totalLessons: 40
    },
    {
        id: 45,
        firstName: "Zhasulan",
        lastName: "Maratov",
        age: 13,
        branch: "Zhandosova",
        coach: "Zakir Anvarovich",
        razryad: "2nd",
        status: "active",
        currentLevel: 6,
        currentLesson: 26,
        totalLessons: 40
    },
    {
        id: 46,
        firstName: "Akmaral",
        lastName: "Zhumagalieva",
        age: 10,
        branch: "Zhandosova",
        coach: "Arman Ermekovich",
        razryad: null,
        status: "active",
        currentLevel: 3,
        currentLesson: 12,
        totalLessons: 40
    },
    {
        id: 47,
        firstName: "Galymzhan",
        lastName: "Shayakhmetov",
        age: 15,
        branch: "Zhandosova",
        coach: "Arman Ermekovich",
        razryad: "KMS",
        status: "active",
        currentLevel: 8,
        currentLesson: 39,
        totalLessons: 40
    },
    {
        id: 48,
        firstName: "Raushan",
        lastName: "Serikova",
        age: 8,
        branch: "Zhandosova",
        coach: "Arman Ermekovich",
        razryad: null,
        status: "active",
        currentLevel: 1,
        currentLesson: 3,
        totalLessons: 40
    },
    {
        id: 49,
        firstName: "Temirlan",
        lastName: "Kassenov",
        age: 12,
        branch: "Zhandosova",
        coach: "Arman Ermekovich",
        razryad: "2nd",
        status: "active",
        currentLevel: 5,
        currentLesson: 21,
        totalLessons: 40
    },
    {
        id: 50,
        firstName: "Gaukhar",
        lastName: "Tursynbekova",
        age: 11,
        branch: "Zhandosova",
        coach: "Arman Ermekovich",
        razryad: "3rd",
        status: "active",
        currentLevel: 4,
        currentLesson: 19,
        totalLessons: 40
    },

    // Abaya Rozybakieva Branch (10 students)
    {
        id: 51,
        firstName: "Murat",
        lastName: "Tashkenbaev",
        age: 13,
        branch: "Abaya Rozybakieva",
        coach: "Vasiliev Vasiliy",
        razryad: "1st",
        status: "active",
        currentLevel: 6,
        currentLesson: 29,
        totalLessons: 40
    },
    {
        id: 52,
        firstName: "Aida",
        lastName: "Kozhakhmetova",
        age: 9,
        branch: "Abaya Rozybakieva",
        coach: "Vasiliev Vasiliy",
        razryad: null,
        status: "active",
        currentLevel: 2,
        currentLesson: 7,
        totalLessons: 40
    },
    {
        id: 53,
        firstName: "Nurislam",
        lastName: "Smagul",
        age: 14,
        branch: "Abaya Rozybakieva",
        coach: "Vasiliev Vasiliy",
        razryad: "KMS",
        status: "active",
        currentLevel: 7,
        currentLesson: 34,
        totalLessons: 40
    },
    {
        id: 54,
        firstName: "Aizharkyn",
        lastName: "Musina",
        age: 10,
        branch: "Abaya Rozybakieva",
        coach: "Vasiliev Vasiliy",
        razryad: "3rd",
        status: "active",
        currentLevel: 3,
        currentLesson: 14,
        totalLessons: 40
    },
    {
        id: 55,
        firstName: "Zhangir",
        lastName: "Amangeldin",
        age: 12,
        branch: "Abaya Rozybakieva",
        coach: "Vasiliev Vasiliy",
        razryad: "2nd",
        status: "active",
        currentLevel: 5,
        currentLesson: 23,
        totalLessons: 40
    },
    {
        id: 56,
        firstName: "Zhuldyz",
        lastName: "Abylkasymova",
        age: 11,
        branch: "Abaya Rozybakieva",
        coach: "Vasiliev Vasiliy",
        razryad: "3rd",
        status: "active",
        currentLevel: 4,
        currentLesson: 17,
        totalLessons: 40
    },
    {
        id: 57,
        firstName: "Serik",
        lastName: "Musaev",
        age: 15,
        branch: "Abaya Rozybakieva",
        coach: "Vasiliev Vasiliy",
        razryad: "KMS",
        status: "active",
        currentLevel: 8,
        currentLesson: 40,
        totalLessons: 40
    },
    {
        id: 58,
        firstName: "Moldyr",
        lastName: "Baigarayeva",
        age: 8,
        branch: "Abaya Rozybakieva",
        coach: "Vasiliev Vasiliy",
        razryad: null,
        status: "active",
        currentLevel: 1,
        currentLesson: 6,
        totalLessons: 40
    },
    {
        id: 59,
        firstName: "Nurdaulet",
        lastName: "Kudaibergenov",
        age: 13,
        branch: "Abaya Rozybakieva",
        coach: "Vasiliev Vasiliy",
        razryad: "1st",
        status: "active",
        currentLevel: 6,
        currentLesson: 28,
        totalLessons: 40
    },
    {
        id: 60,
        firstName: "Aigerim",
        lastName: "Saparbayeva",
        age: 10,
        branch: "Abaya Rozybakieva",
        coach: "Vasiliev Vasiliy",
        razryad: "3rd",
        status: "active",
        currentLevel: 3,
        currentLesson: 13,
        totalLessons: 40
    },

    // Almaty 1 Branch (10 students)
    {
        id: 61,
        firstName: "Alikhan",
        lastName: "Zhakenov",
        age: 12,
        branch: "Almaty 1",
        coach: "Karmenov Berik",
        razryad: "2nd",
        status: "active",
        currentLevel: 5,
        currentLesson: 24,
        totalLessons: 40
    },
    {
        id: 62,
        firstName: "Asel",
        lastName: "Rakhmanova",
        age: 9,
        branch: "Almaty 1",
        coach: "Karmenov Berik",
        razryad: null,
        status: "active",
        currentLevel: 2,
        currentLesson: 9,
        totalLessons: 40
    },
    {
        id: 63,
        firstName: "Abzal",
        lastName: "Kuanyshev",
        age: 14,
        branch: "Almaty 1",
        coach: "Karmenov Berik",
        razryad: "1st",
        status: "active",
        currentLevel: 7,
        currentLesson: 31,
        totalLessons: 40
    },
    {
        id: 64,
        firstName: "Meruyert",
        lastName: "Bekenova",
        age: 11,
        branch: "Almaty 1",
        coach: "Karmenov Berik",
        razryad: "3rd",
        status: "active",
        currentLevel: 4,
        currentLesson: 16,
        totalLessons: 40
    },
    {
        id: 65,
        firstName: "Temirzhan",
        lastName: "Seitov",
        age: 13,
        branch: "Almaty 1",
        coach: "Karmenov Berik",
        razryad: "2nd",
        status: "active",
        currentLevel: 6,
        currentLesson: 27,
        totalLessons: 40
    },
    {
        id: 66,
        firstName: "Aikorkem",
        lastName: "Zhumasheva",
        age: 10,
        branch: "Almaty 1",
        coach: "Karmenov Berik",
        razryad: null,
        status: "active",
        currentLevel: 3,
        currentLesson: 11,
        totalLessons: 40
    },
    {
        id: 67,
        firstName: "Nurzhan",
        lastName: "Iskakov",
        age: 15,
        branch: "Almaty 1",
        coach: "Karmenov Berik",
        razryad: "KMS",
        status: "active",
        currentLevel: 8,
        currentLesson: 36,
        totalLessons: 40
    },
    {
        id: 68,
        firstName: "Zhibek",
        lastName: "Orazgalieva",
        age: 8,
        branch: "Almaty 1",
        coach: "Karmenov Berik",
        razryad: null,
        status: "active",
        currentLevel: 1,
        currentLesson: 5,
        totalLessons: 40
    },
    {
        id: 69,
        firstName: "Aldiyar",
        lastName: "Mynbayev",
        age: 12,
        branch: "Almaty 1",
        coach: "Karmenov Berik",
        razryad: "2nd",
        status: "active",
        currentLevel: 5,
        currentLesson: 22,
        totalLessons: 40
    },
    {
        id: 70,
        firstName: "Arailym",
        lastName: "Tursynova",
        age: 11,
        branch: "Almaty 1",
        coach: "Karmenov Berik",
        razryad: "3rd",
        status: "active",
        currentLevel: 4,
        currentLesson: 18,
        totalLessons: 40
    }
];

// Coach data - 9 coaches across 7 branches
const coaches = [
    {
        id: 1,
        firstName: "Asylkhan",
        lastName: "Akbaevich",
        branch: "Debut",
        email: "asylkhan@chessempire.kz",
        phone: "+7 (777) 111-11-11"
    },
    {
        id: 2,
        firstName: "Tanibergen",
        lastName: "Aibekovich",
        branch: "Almaty Arena",
        email: "tanibergen@chessempire.kz",
        phone: "+7 (777) 222-22-22"
    },
    {
        id: 3,
        firstName: "Alinur",
        lastName: "Serikovich",
        branch: "Halyk Arena",
        email: "alinur@chessempire.kz",
        phone: "+7 (777) 333-33-33"
    },
    {
        id: 4,
        firstName: "Zakir",
        lastName: "Anvarovich",
        branch: "Zhandosova",
        email: "zakir@chessempire.kz",
        phone: "+7 (777) 444-44-44"
    },
    {
        id: 5,
        firstName: "Arman",
        lastName: "Ermekovich",
        branch: "Zhandosova",
        email: "arman@chessempire.kz",
        phone: "+7 (777) 555-55-55"
    },
    {
        id: 6,
        firstName: "Khantuev",
        lastName: "Alexander",
        branch: "Halyk Arena",
        email: "alexander@chessempire.kz",
        phone: "+7 (777) 666-66-66"
    },
    {
        id: 7,
        firstName: "Nurgalimov",
        lastName: "Chingis",
        branch: "Gagarin Park",
        email: "chingis@chessempire.kz",
        phone: "+7 (777) 777-77-77"
    },
    {
        id: 8,
        firstName: "Karmenov",
        lastName: "Berik",
        branch: "Almaty 1",
        email: "berik@chessempire.kz",
        phone: "+7 (777) 888-88-88"
    },
    {
        id: 9,
        firstName: "Vasiliev",
        lastName: "Vasiliy",
        branch: "Abaya Rozybakieva",
        email: "vasiliy@chessempire.kz",
        phone: "+7 (777) 999-99-99"
    }
];

// Branch data - All 7 branches
const branches = [
    {
        id: 1,
        name: "Gagarin Park",
        location: "Almaty, Gagarin Park",
        phone: "+7 (727) 250-12-34",
        email: "gagarinpark@chessempire.kz"
    },
    {
        id: 2,
        name: "Debut",
        location: "Almaty, Auezov District",
        phone: "+7 (727) 251-23-45",
        email: "debut@chessempire.kz"
    },
    {
        id: 3,
        name: "Almaty Arena",
        location: "Almaty, Bostandyk District",
        phone: "+7 (727) 252-34-56",
        email: "arena@chessempire.kz"
    },
    {
        id: 4,
        name: "Halyk Arena",
        location: "Almaty, Almaly District",
        phone: "+7 (727) 253-45-67",
        email: "halyk@chessempire.kz"
    },
    {
        id: 5,
        name: "Zhandosova",
        location: "Almaty, Zhandosov Street",
        phone: "+7 (727) 254-56-78",
        email: "zhandosova@chessempire.kz"
    },
    {
        id: 6,
        name: "Abaya Rozybakieva",
        location: "Almaty, Abay Avenue",
        phone: "+7 (727) 255-67-89",
        email: "abaya@chessempire.kz"
    },
    {
        id: 7,
        name: "Almaty 1",
        location: "Almaty, Railway Station Area",
        phone: "+7 (727) 256-78-90",
        email: "almaty1@chessempire.kz"
    }
];
